version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8082:80"
    depends_on:
      - postgres

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      DB_CONN_STR: postgres://user:password@postgres:5432/mydb?sslmode=disable
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    ports:
      - "8081:8081"
    environment:
      BACKEND_URL: http://backend:8080
    depends_on:
      - backend

  db-init:
    build: ./db-init
    environment:
      DB_CONN_STR: postgres://user:password@postgres:5432/mydb?sslmode=disable
    depends_on:
      - postgres

volumes:
  pgdata:
